# Generated by Django 5.2.6 on 2025-09-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='user_id',
        ),
    ]
